name: ZMK firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: zmk
    steps:
      - uses: actions/checkout@v4
      - uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
